// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCziE0x-pJKlG4sCptWoCdTKWE-G7CJsNc',
    appId: '1:576873723625:web:fdd03ddf486ae3f17be278',
    messagingSenderId: '576873723625',
    projectId: 'garbo-85be1',
    authDomain: 'garbo-85be1.firebaseapp.com',
    storageBucket: 'garbo-85be1.appspot.com',
    measurementId: 'G-VMCVJ1YGC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wowkyK_iDUFxD7FeRRDSM5T6q7FQKdI',
    appId: '1:576873723625:android:bdb8170dcd48f2d57be278',
    messagingSenderId: '576873723625',
    projectId: 'garbo-85be1',
    storageBucket: 'garbo-85be1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNSGld89TfRgxutT0ofSbRjibWQhNqnSI',
    appId: '1:576873723625:ios:ac8cefc4a30e90ba7be278',
    messagingSenderId: '576873723625',
    projectId: 'garbo-85be1',
    storageBucket: 'garbo-85be1.appspot.com',
    iosBundleId: 'com.example.garbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNSGld89TfRgxutT0ofSbRjibWQhNqnSI',
    appId: '1:576873723625:ios:ac8cefc4a30e90ba7be278',
    messagingSenderId: '576873723625',
    projectId: 'garbo-85be1',
    storageBucket: 'garbo-85be1.appspot.com',
    iosBundleId: 'com.example.garbo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCziE0x-pJKlG4sCptWoCdTKWE-G7CJsNc',
    appId: '1:576873723625:web:fff37edc366eeb297be278',
    messagingSenderId: '576873723625',
    projectId: 'garbo-85be1',
    authDomain: 'garbo-85be1.firebaseapp.com',
    storageBucket: 'garbo-85be1.appspot.com',
    measurementId: 'G-FNGHSG8L08',
  );
}
